function t232_expandtext(recid){$("#rec"+recid).find(".t232__text").toggle()}
t422_setHeight=function(recid){if($(window).width()>960){t422_checkEqualHeight(recid)}else{$('#rec'+recid+' .t422__img-mobile').height(200);$('#rec'+recid+' .t422__text').height('auto')}};t422_checkEqualHeight=function(recid){var t422__txtel=$('#rec'+recid+' .t422__text');var t422__imgel=$('#rec'+recid+' .t422__img');var t422__borderwidth=0;if(t422__txtel.css("border-top-width")&&t422__txtel.css("border-top-width")[1]!='p'){t422__borderwidth=+(t422__txtel.css("border-top-width")[0]+t422__txtel.css('border-top-width')[1])}else{if(t422__txtel.css("border-top-width"))
t422__borderwidth=+(t422__txtel.css("border-top-width")[0])}
if(t422__imgel.height()<(t422__txtel.height()+t422__borderwidth*2)){t422__imgel.height(t422__txtel.height()+t422__borderwidth*2)}else{if((t422__imgel.height()-t422__borderwidth*2)>t422__txtel.height()){t422__txtel.height(t422__imgel.height()-t422__borderwidth*2)}}};function t456_setListMagin(recid,imglogo){if($(window).width()>980){var t456__menu=$('#rec'+recid+' .t456');var t456__leftpart=t456__menu.find('.t456__leftwrapper');var t456__listpart=t456__menu.find('.t456__list');if(imglogo){t456__listpart.css("margin-right",t456__leftpart.width())}else{t456__listpart.css("margin-right",t456__leftpart.width()+30)}}}
function t456_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t456__list_item a[href='"+url+"']").addClass("t-active");$(".t456__list_item a[href='"+url+"/']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t456__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t456__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t456_checkAnchorLinks(recid){if($(window).width()>=960){var t456_navLinks=$("#rec"+recid+" .t456__list_item a:not(.tooltipstered)[href*='#']");if(t456_navLinks.length>0){t456_catchScroll(t456_navLinks)}}}
function t456_catchScroll(t456_navLinks){var t456_clickedSectionId=null,t456_sections=new Array(),t456_sectionIdTonavigationLink=[],t456_interval=100,t456_lastCall,t456_timeoutId;t456_navLinks=$(t456_navLinks.get().reverse());t456_navLinks.each(function(){var t456_cursection=t456_getSectionByHref($(this));if(typeof t456_cursection.attr("id")!="undefined"){t456_sections.push(t456_cursection)}
t456_sectionIdTonavigationLink[t456_cursection.attr("id")]=$(this)});$(window).bind('resize',t_throttle(function(){t456_updateSectionsOffsets(t456_sections)},200));$('.t456').bind('displayChanged',function(){t456_updateSectionsOffsets(t456_sections)});setInterval(function(){t456_updateSectionsOffsets(t456_sections)},5000);setTimeout(function(){t456_updateSectionsOffsets(t456_sections);t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},1000);t456_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t456_navLinks.removeClass('t-active');t456_sectionIdTonavigationLink[t456_getSectionByHref($(this)).attr("id")].addClass('t-active');t456_clickedSectionId=t456_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t456_now=new Date().getTime();if(t456_lastCall&&t456_now<(t456_lastCall+t456_interval)){clearTimeout(t456_timeoutId);t456_timeoutId=setTimeout(function(){t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)},t456_interval-(t456_now-t456_lastCall))}else{t456_lastCall=t456_now;t456_clickedSectionId=t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId)}})}
function t456_updateSectionsOffsets(sections){$(sections).each(function(){var t456_curSection=$(this);t456_curSection.attr("data-offset-top",t456_curSection.offset().top)})}
function t456_getSectionByHref(curlink){var t456_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t456_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t456_curLinkValue.substring(1)+"']")}}
function t456_highlightNavLinks(t456_navLinks,t456_sections,t456_sectionIdTonavigationLink,t456_clickedSectionId){var t456_scrollPosition=$(window).scrollTop(),t456_valueToReturn=t456_clickedSectionId;if(t456_sections.length!=0&&t456_clickedSectionId==null&&t456_sections[t456_sections.length-1].attr("data-offset-top")>(t456_scrollPosition+300)){t456_navLinks.removeClass('t-active');return null}
$(t456_sections).each(function(e){var t456_curSection=$(this),t456_sectionTop=t456_curSection.attr("data-offset-top"),t456_id=t456_curSection.attr('id'),t456_navLink=t456_sectionIdTonavigationLink[t456_id];if(((t456_scrollPosition+300)>=t456_sectionTop)||(t456_sections[0].attr("id")==t456_id&&t456_scrollPosition>=$(document).height()-$(window).height())){if(t456_clickedSectionId==null&&!t456_navLink.hasClass('t-active')){t456_navLinks.removeClass('t-active');t456_navLink.addClass('t-active');t456_valueToReturn=null}else{if(t456_clickedSectionId!=null&&t456_id==t456_clickedSectionId){t456_valueToReturn=null}}
return!1}});return t456_valueToReturn}
function t456_setPath(){}
function t456_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t456_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t456_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t456").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t456_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t456"),burger=el.find(".t456__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t456_opened")});$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t552_init(recid,ratio){var t552__el=$("#rec"+recid),t552__image=t552__el.find(".t552__blockimg:first");t552__setHeight(recid,t552__image,ratio);var t552__doResize;$(window).resize(function(){clearTimeout(t552__doResize);t552__doResize=setTimeout(function(){t552__setHeight(recid,t552__image,ratio)},200)})}
function t552__setHeight(recid,image,ratio){$("#rec"+recid+" .t552__blockimg").css("height",Math.round(image.innerWidth()*ratio))}
function t557_init(recid,snowtype){$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_1.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_2.png').load(function(){$(this).remove()});$('<img/>').attr('src','https://static.tildacdn.com/img/snowflakes_3.png').load(function(){$(this).remove();t557__addSnow(recid,snowtype)})}
function t557__addSnow(recid,snowtype){var el=$('#rec'+recid),t557_ids=el.find('.t557__snow-recid-holder').attr('data-snow-rec-ids').split(',');if(t557_ids!=""){t557_ids.forEach(function(rec_id,i,arr){var t557_zeroattr=$('#rec'+rec_id).attr('data-record-type');if(t557_zeroattr==396){var t557_wrappertype=" .t396__artboard"}else{var t557_wrappertype=" .t-cover"}
var t557_cover=document.querySelector('#rec'+rec_id+t557_wrappertype);if(t557_cover!=null){var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.appendChild(t557_snow)}})}else{t557_cover=$('.t-cover').first();var t557_snow=document.createElement('div');t557_snow.className=snowtype;t557_cover.append(t557_snow)}
$('.'+snowtype).animate({"opacity":"1"},1000,function(){})}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).load(function(){t570_setMapHeight(recid)});$(window).resize(function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t651_initPopup(recid){if(window.$isMobile){if($('#rec'+recid+' .t651__phone').length==0){return}
t651_phone=$('#rec'+recid+' .t651__phone').html().replace(/\s+/g,'');$('#rec'+recid+' .t651__btn').click(function(){window.location.href="tel:"+t651_phone;$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none')});return}
$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t651__popup'),analitics=el.attr('data-track-popup'),hook="TildaCallBackWidget"+recid,obj=$('#rec'+recid+' .t651__btn');obj.click(function(e){if(obj.hasClass("t651__btn_active")){t651_closePopup();return}
obj.addClass("t651__btn_active");t651_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}
function t651_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t651__popup');$('.t651__btn_wrapper').removeClass('t651__btn_animate');$('.t651__btn-text').css('display','none');popup.css('display','block');setTimeout(function(){popup.addClass('t651__popup_show')},50);$(document).keydown(function(e){if(e.keyCode==27){t651_closePopup()}})}
function t651_closePopup(){$('.t651__btn').removeClass('t651__btn_active');$('.t651__popup').removeClass('t651__popup_show');setTimeout(function(){$('.t651__popup').not('.t651__popup_show').css('display','none')},300)}
function t651_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t696_onSuccess(t696_form){var t696_inputsWrapper=t696_form.find('.t-form__inputsbox');var t696_inputsHeight=t696_inputsWrapper.height();var t696_inputsOffset=t696_inputsWrapper.offset().top;var t696_inputsBottom=t696_inputsHeight+t696_inputsOffset;var t696_targetOffset=t696_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t696_target=t696_targetOffset-200}else{var t696_target=t696_targetOffset-100}
if(t696_targetOffset>$(window).scrollTop()||($(document).height()-t696_inputsBottom)<($(window).height()-100)){t696_inputsWrapper.addClass('t696__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t696_target},400);setTimeout(function(){t696_inputsWrapper.addClass('t696__inputsbox_hidden')},400)}
var successurl=t696_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t734_init(recid){var rec=$('#rec'+recid);if($('body').find('.t830').length>0){setTimeout(function(){t_sldsInit(recid)},500)}else{t_sldsInit(recid)}
rec.find('.t734').bind('displayChanged',function(){t_slds_updateSlider(recid)})}
function t849_init(recid){var rec=$('#rec'+recid);var toggler=rec.find('.t849__header');toggler.click(function(){$(this).toggleClass('t849__opened');$(this).next().slideToggle();if(window.lazy=='y'){t_lazyload_update()}})}